[package]
authors = ["Augustus Mayo <gusmayo@gmail.com>"]
name = "masque"
version = "0.1.0"

[dependencies]
base64 = "0.9.2"
clap = "2.31.2"
futures = "0.1.24"
hyper = "0.12"
hyper-tls = "0.3.0"
log = "0.4.1"
